config/routes.rb
require 'override_csp'

Rails.application.routes.draw do
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  end

  direct :rails_public_blob do |blob|
    if Rails.env.development? || Rails.env.test? || ENV['CLOUDFRONT_HOST'].blank?
      route =
        if blob.is_a?(ActiveStorage::Variant) || blob.is_a?(ActiveStorage::VariantWithRecord)
          :rails_representation
        else
          :rails_blob
        end
      route_for(route, blob, only_path: true)
    else
      Cloudfront::GenerateSignedUrlService.new(blob).generate_url
    end
  end

  post '/graphql', to: 'graphql#execute'

  devise_for :users, only: %i[sessions omniauth_callbacks], controllers: { sessions: 'users/sessions', omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    post 'users/send_reset_password_email', controller: 'users/sessions', action: 'send_reset_password_email', as: 'user_send_reset_password_email'
    get 'users/token', controller: 'users/sessions', action: 'token', as: 'user_token'
    get 'users/auth_callback', controller: 'users/sessions', action: 'auth_callback', as: 'user_auth_callback'
    get 'users/reset_password', controller: 'users/sessions', action: 'reset_password', as: 'reset_password'
    post 'users/update_password', controller: 'users/sessions', action: 'update_password', as: 'update_password'
    get 'users/sign_in_with_email', controller: 'users/sessions', action: 'sign_in_with_email', as: 'sign_in_with_email'
    get 'users/request_password_reset', controller: 'users/sessions', action: 'request_password_reset', as: 'request_password_reset'

    if Rails.env.development?
      get 'users/auth/developer', controller: 'users/omniauth_callbacks', action: 'passthru', as: 'user_developer_omniauth_authorize'
      post 'users/auth/developer/callback', controller: 'users/omniauth_callbacks', action: 'developer'
    end
  end

  get 'users/delete_account', controller: 'users', action: 'delete_account', as: 'delete_account'

  post 'users/email_bounce', controller: 'users/postmark_webhook', action: 'email_bounce'

  get 'users/update_email', controller: 'users', action: 'update_email', as: 'update_email'

  authenticate :user, ->(u) { AdminUser.where(email: u.email).present? } do
    mount Delayed::Web::Engine, at: '/jobs'
    mount OverrideCsp.new(Flipper::UI.app(Flipper)), at: '/toggle'
  end

  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  resource :applicants, only: [] do
    get '/:token/enroll', action: 'enroll', as: 'enroll'
  end

  resources :notifications, only: %i[show]

  resource :school, only: [] do
    get 'customize'
    get 'admins'
    get 'standing'
    get 'code_of_conduct'
    patch 'code_of_conduct', action: 'update_code_of_conduct'
    patch 'toggle_standing'
    post 'images'

    resources :standings, controller: 'schools/standings', except: [:index, :show]
  end

  namespace :school, module: 'schools' do
    [
      '/',
      'courses',
      'courses/new',
      'courses/:course_id',
      'courses/:course_id/details',
      'courses/:course_id/images',
      'courses/:course_id/actions',
      'courses/:course_id/cohorts',
      'courses/:course_id/cohorts/new',
      'cohorts/:cohort_id/details',
      'cohorts/:cohort_id/actions',
      'courses/:course_id/students',
      'courses/:course_id/students/new',
      'courses/:course_id/students/import',
      'students/:student_id/details',
      'students/:student_id/actions',
      'students/:student_id/standing',
      'courses/:course_id/teams',
      'courses/:course_id/teams/new',
      'teams/:team_id/details',
      'teams/:team_id/actions',
    ].each do |path|
      get path, action: 'school_router'
    end

    resources :faculty, only: %i[create update destroy], as: 'coaches', path: 'coaches' do
      collection do
        get '/', action: 'school_index'
      end
    end

    resources :calendars, only: %i[update], controller: 'calendars'
    resources :calendar_events, only: %i[update destroy], controller: 'calendar_events'

    resources :targets, only: [] do
      resource :content_block, only: %i[create]
      member do
        get 'action', action: 'action'
        patch 'update_action', action: 'update_action'
      end
    end

    resources :cohorts, only: [] do
      member do
        post 'bulk_import_students'
      end
    end

    resources :assignments, only: [] do
      member do
        patch :update_milestone_number
      end
    end

    resources :courses, only: [] do
      member do
        get 'applicants'
        get 'calendar_events'
        get 'curriculum'
        get 'exports'
        get 'authors'
        get 'certificates'
        post 'certificates', action: 'create_certificate'
        get 'evaluation_criteria'
        post 'attach_images'
        get 'calendar_month_data'
        get 'assignments'
      end

      resources :calendar_events, only: %i[new create show edit], controller: 'calendar_events'

      resources :calendars, only: %i[new create edit], controller: 'calendars'

      resources :authors, only: %w[show new]

      resources :applicants, only: :show do
        member do
          get 'actions', action: :show
          get 'details', action: :show
        end
      end

      resources :targets, only: [] do
        member do
          get 'content'
          get 'details'
          get 'versions'
        end
      end

      resources :levels, only: %i[create]

      resources :faculty, as: 'coaches', path: 'coaches', only: [] do
        collection do
          get '/', action: 'course_index'
        end
      end

      get 'students'
      post 'delete_coach_enrollment'
      post 'update_coach_enrollments'
    end

    resources :students, as: 'students', path: 'students', except: %i[index] do
      collection do
        post 'team_up'
      end
    end

    resources :levels, only: %i[update] do
      resources :target_groups, only: %i[create]
    end

    resources :target_groups, only: %i[update]

    resources :communities, only: %i[index]
  end

  resources :organisations, only: %i[show index] do
    resources :cohorts, module: 'organisations', only: %i[show] do
      member do
        get 'students'
      end
    end

    resources :courses,  module: 'organisations', only: [] do
      member do
        get 'active_cohorts'
        get 'ended_cohorts'
      end
    end
  end

  namespace :org, module: 'organisations' do
    resources :students, only: %[show] do
      member do
        get 'submissions'
        get 'standing'
      end
    end
  end

  resources :communities, only: %i[show] do
    member do
      get 'new_topic'
      get ':name', action: 'show'
    end
  end

  get 'topics/:id(/:title)', controller: 'topics', action: 'show', as: 'topic'

  get 'posts/:id/versions', controller: 'posts', action: 'versions', as: 'post_version'

  get 'dashboard', controller: 'users', action: 'dashboard', as: 'dashboard'

  resource :user, only: %i[edit] do
    post 'upload_avatar'
    post 'clear_discord_id'
    get 'discord_account_required'
    get 'standing'
  end

  resources :timeline_event_files, only: %i[create] do
    member do
      get 'download'
    end
  end

  scope 'coaches', controller: 'faculty' do
    get '/', action: 'index', as: 'coaches_index'
  end

  # Student show
  scope 'students', controller: 'students' do
    get '/:id/report', action: 'report', as: 'student_report'
  end

  get 'styleguide', to: 'home#styleguide', constraints: DevelopmentConstraint.new

  get 'manifest', to: 'home#manifest'
  get 'offline', to: 'home#offline'
  root 'home#index'

  get 'agreements/:agreement_type', as: 'agreement', controller: 'home', action: 'agreement'

  resources :targets, only: %i[show] do
    member do
      get 'details_v2'
      get ':slug', action: 'show'
      post 'mark_as_read'
    end
  end

  resources :timeline_events, only: %i[show], path: 'submissions' do
    member do
      get 'review', action: 'review'
    end
  end

  resources :courses, only: %i[show] do
    member do
      get 'review', action: 'review'
      get 'cohorts', action: 'cohorts'
      get 'calendar', action: 'calendar'
      get 'calendar_month_data', action: 'calendar_month_data'
      get 'leaderboard', action: 'leaderboard'
      get 'curriculum', action: 'curriculum'
      get 'report', action: 'report'
      get 'apply', action: 'apply'
      post 'apply', action: 'process_application'
      get '/(:name)', action: 'show'
    end
  end

  resources :cohorts, only: %i[show] do
    member do
      get 'students', action: 'students'
    end
  end

  resources :markdown_attachments, only: %i[create] do
    member do
      get '/:token', action: 'download', as: 'download'
    end
  end

  get '/c/:serial_number', to: 'issued_certificates#verify', as: :issued_certificate
  get '/help/:document', to: 'help#show'
  get '/oauth/:provider', to: 'home#oauth', as: 'oauth', constraints: SsoConstraint.new
  get '/oauth_error', to: 'home#oauth_error', as: 'oauth_error'

  # Allow developers to simulate the error pages.
  get '/errors/:error_type', to: 'errors#simulate', constraints: DevelopmentConstraint.new

  get '/service-worker.js', to: 'home#service_worker'
  get '/favicon.ico', to: 'home#favicon'
end

app/views/shared/_breadcrumbs.html.erb
<ol class="list-none inline-flex space-x-1 text-gray-400 items-center pb-3">
  <% crumbs.each do |title, link| %>
    <li>
      <div class="flex items-center">
        <%= link_to link.presence || '#',  class: link.presence ? "max-w-[16ch] sm:max-w-[30ch] overflow-hidden whitespace-nowrap text-ellipsis text-sm underline font-medium text-gray-600 hover:text-primary-500 transition-colors duration-200" : "max-w-[16ch] sm:max-w-[30ch] overflow-hidden whitespace-nowrap text-ellipsis text-sm font-medium text-gray-500" do %>
          <span><%= title %></span>
        <% end %>
        <% if link %>
          <span><i class="if i-chevron-right-regular ms-1"></i></span>
        <% end %>
      </div>
    </li>
  <% end %>
</ol>

app/views/shared/_cohort_overview.html.erb
<div class="md:pt-18 bg-gray-50 relative">
  <section class="bg-gray-50">
    <div class="max-w-5xl mx-auto px-4 pt-4 md:px-6 md:pt-6">
      <% if @organisation %>
        <div class="mt-4 overflow-x-auto">
          <%= render 'shared/breadcrumbs', crumbs: [[t('shared.my_org'), "/organisations"], [@organisation.name, organisation_path(@organisation)], [@cohort.course.name, active_cohorts_organisation_course_path(@organisation, @cohort.course)], [@cohort.name]] %>
        </div>
      <% end %>
      <h1 class="text-xl md:text-3xl font-bold mt-4 break-words">
        <%= @cohort.name %>
      </h1>
      <p class="text-sm font-medium"><%= @cohort.course.name %></p>
      <div class="mt-6 flex gap-4 items-center border-b border-gray-300 text-sm">
        <p class="p-2 border-b-2 border-primary-500 text-primary-500 font-semibold"><%= t('.overview_link') %></p>
        <%= link_to t('.students_link'), students_path, class: "p-2 hover:text-primary-500 hover:bg-primary-100" %>
      </div>
    </div>
  </section>
  <%
    total_students_count = @presenter.counts[:total]
    milestone_completion_status = @presenter.milestone_completion_status if total_students_count > 0
  %>
  <section class="bg-white">
    <div class="grid md:grid-cols-12 gap-6 max-w-5xl p-4 md:p-6 mx-auto">
      <div class="md:col-span-8 mt-2 order-2 md:order-1">
        <% if (total_students_count > 0 or milestone_completion_status.present?) && (@presenter.milestone_targets.present?) %>
          <h3 class="font-semibold"><%= t('.student_distribution_by_milestone') %></h3>
          <div class="mt-4">
            <div class="max-w-5xl mx-auto">
              <div class="grid gap-x-8 gap-y-6">
                <% @presenter.milestone_targets.each do |target| %>
                  <% milestone_target_stats = milestone_completion_status[target.id] %>
                  <div>
                    <div class="flex justify-between">
                      <p class="text-xs font-medium"><%= "#{t("shared.m")}#{target.assignments.first.milestone_number}: #{target.title}" %></p>
                      <div class="flex space-x-2">
                        <p class="text-xs font-medium text-gray-500"><%= "#{milestone_target_stats[:students_count]}/#{total_students_count}" %></p>
                        <p class="text-center text-xs font-medium rounded-sm px-1 bg-gray-200"><%= "#{milestone_target_stats[:percentage]}%" %></p>
                      </div>
                    </div>
                    <%= link_to @organisation ? students_organisation_cohort_path(@organisation, @cohort, milestone_completed: "#{target.id};#{t("shared.m")}#{target.assignments.first.milestone_number}: #{target.title}") : students_cohort_path(milestone_completed: "#{target.id};#{t("shared.m")}#{target.assignments.first.milestone_number}: #{target.title}"), class:'flex relative bg-gray-200 border border-transparent rounded-md overflow-hidden mt-1 hover:border-primary-300 hover:bg-primary-100 focus:outline-none focus:bg-primary-100 focus:text-primary-500 focus:ring-2 focus:ring-focusColor-500 transition' do %>
                      <span style="<%= "width: #{milestone_target_stats[:percentage]}%" %>" class="flex h-3 text-center bg-green-500"></span>
                    <% end %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        <% else %>
          <div class="max-w-5xl mx-auto text-center justify-center items-center text-sm italic mt-4 pt-4">
            <%= t('.no_students') if total_students_count == 0 %>
            <%= t('.no_milestone_targets') if @presenter.milestone_targets.empty? %>
          </div>
        <% end %>
      </div>
      <div class="mt-4 md:col-span-4 order-1 md:order-2">
        <div class="grid grid-cols-1 gap-5 bg-gray-50 p-4 rounded-md">
          <div class="p-4 md:p-5 bg-white flex flex-col gap-2 shadow rounded-lg">
            <p class="text-sm text-gray-600"><%= t('.total_students') %></p>
            <p class="text-3xl font-bold"><%= total_students_count %></p>
            <%= link_to students_path, class: "text-sm font-medium text-primary-500 hover:text-primary-800 hover:underline" do %>
              <span><%= t('.view_all')%></span><i class="if i-arrow-right-regular rtl:rotate-180 inline-block text-primary-500 ms-2" aria-hidden="true"></i>
            <% end %>
          </div>
          <div class="p-4 md:p-5 bg-white flex flex-col gap-2 shadow rounded-lg">
            <p class="text-sm text-gray-600"><%= t('.students_completed') %></p>
            <p class="text-3xl font-bold"><%= @presenter.counts[:completed] %></p>
            <%= link_to students_completed_path, class: "text-sm font-medium text-primary-500 hover:text-primary-800 hover:underline" do %>
              <span><%= t('.view_all')%></span><i class="if i-arrow-right-regular rtl:rotate-180 inline-block text-primary-500 ms-2" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/shared/_standing_shield.html.erb
<svg class="<%= size_classes %>" viewBox="0 0 49 49" fill="<%= color %>" xmlns="http://www.w3.org/2000/svg">
  <path id="outer_shield" d="M7.83377 11.1092L24.3192 4.25812C24.5648 4.15603 24.8411 4.15603 25.0867 4.25812L41.5721 11.1092C41.9452 11.2643 42.1884 11.6267 42.1884 12.0308V23.4764C42.1884 29.045 36.0992 38.8206 25.1233 43.8751C24.8583 43.9971 24.5481 43.9924 24.2858 43.8646C12.3439 38.0435 7.21753 29.0512 7.21753 23.4764V12.0308C7.21753 11.6267 7.46067 11.2643 7.83377 11.1092Z" fill="<%= color %>" class="opacity-75"/>
  <path id="inner_shield" d="M11.4346 13.229L24.3193 7.87433C24.5649 7.77224 24.8412 7.77224 25.0868 7.87433L37.9715 13.229C38.3446 13.3841 38.5877 13.7478 38.5877 14.1518V23.1022C38.5877 27.5095 33.7843 35.2355 25.1228 39.2605C24.8582 39.3834 24.5485 39.3788 24.2866 39.2502C14.8647 34.6267 10.8184 27.5157 10.8184 23.1022V14.1518C10.8184 13.7478 11.0615 13.3841 11.4346 13.229Z" fill="<%= color %>"/>
</svg>

app/views/shared/_student.html.erb
<%
  user = student.user
  report_path = @organisation ? org_student_path(student, filters) : student_report_path(student, filters)
%>
<a href="<%= report_path %>" data-test-class="student" class="block p-5 border border-gray-200 bg-gray-50 rounded-lg hover:bg-primary-50 hover:text-primary-500 hover:border-primary-400">
  <div class="flex justify-between items-center gap-4">
    <div>
      <p class="font-semibold">
        <%= user.name %>
      </p>
      <p class="text-sm text-gray-600">
        <%= user.title %> <span class="px-1" aria-hidden="true">|</span>
        <% if user.last_seen_at.present? %>
          <span title="<%= user.last_seen_at.iso8601 %>"><%= t('.time_ago', time_ago: time_ago_in_words(user.last_seen_at)) %></span>
        <% else %>
          <%= t('.never_signed_in') %>
        <% end %>
      </p>
    </div>
  </div>
</a>

app/views/shared/_students.html.erb
<div class="md:pt-18 bg-gray-50">
  <section class="bg-gray-50">
    <div class="max-w-5xl mx-auto px-4 pt-4 md:px-6 md:pt-6">
      <% if @organisation %>
        <div class="mt-4 overflow-x-auto">
          <%= render 'shared/breadcrumbs', crumbs: [[t('shared.my_org'), '/organisations'], [@organisation.name, organisation_path(@organisation)], [@cohort.course.name, active_cohorts_organisation_course_path(@organisation, @cohort.course)], [@cohort.name]]  %>
        </div>
      <% end %>
      <h1 class="text-xl md:text-3xl font-bold mt-4 break-words">
        <%= @cohort.name %>
      </h1>
      <p class="text-sm font-medium"><%= @cohort.course.name %></p>
      <div class="mt-6 flex gap-4 items-center border-b border-gray-300 text-sm">
        <%= link_to t('shared.cohort_overview.overview_link'), overview_path, class: 'p-2 hover:text-primary-500 hover:bg-primary-100' %>
        <p class="p-2 border-b-2 border-primary-500 text-primary-500 font-semibold"><%= t('shared.cohort_overview.students_link') %></p>
      </div>
    </div>
  </section>
  <section class="bg-white">
    <div class="max-w-5xl mx-auto p-4 md:p-6">
      <div class="mt-2 md:sticky top-18 z-10">
        <div data-re-component="SimpleDropdownFilter" data-re-json="<%= @presenter.filter.to_json %>"></div>
      </div>
      <div class="grid grid-flow-row gap-4 grid-cols-1 md:grid-cols-2  auto-rows-max mt-4">
        <% @presenter.students.each do |student| %>
          <%= render 'shared/student', student: student, filters: @presenter.filters_in_url %>
        <% end %>
      </div>
      <div class="mt-6 flex items-center justify-center">
        <%= paginate @presenter.students %>
      </div>
      <% if @presenter.students.total_pages > 1 %>
        <div class="text-center text-sm italic mt-4">
          <%= t('shared.cohort_students.pagination_notice', page_start: kaminari_page_start(@presenter.students), page_end: kaminari_page_end(@presenter.students), count: @presenter.students.total_count) %>
        </div>
      <% end %>
      <% if @presenter.students.empty? %>
        <div class="text-center text-sm italic mt-4"><%= t('shared.cohort_students.nothing_to_show') %></div>
      <% end %>
    </div>
  </section>
</div>